### PR TITLE
Improve on pyln-client gossmap

### PR DESCRIPTION
**Pull request by m-schmoock**
Is it feasible to work on this PR in your repo so I can add ontop?
I don't have permissions to add to your branch directly.

- Make it more usable for plugin developers to get i.e. fees of channels.
- Adds half-channels objects containing the information about latest channel_update messages.
- Adds `satoshi` capacity of channels by reading `gossip_store_channel_amount` messages.
- Extends testcase

### CODE REVIEW

**Comment by m-schmoock** [comment]
I think we might change the structure and the interface to match more what `lightning-cli listchannels`. Especially returning a list of half channels that have everything (source, dest, fees) is best when trying to compute routing algorithms on it

**Comment by rustyrussell** [comment]
I tried rebasing this, it was an unmitigated disaster.  Fixup patches which move functions, changing them, etc.

This also makes it near impossible to review :(

I've applied the whole thing as a single commit.  I hate doing that, but Ive spent 30 minutes on this so far and it's still unfinished.

**Comment by rustyrussell** [comment]
Actually, managed to salvage it...

**Comment by m-schmoock** [comment]
I tried to keep the fixups relating to your commits as minimal as possible, but fixup 4b7b65e needed to change the order of Classes in the file 😐. Do you know a better way?

**Comment by m-schmoock** [comment]
Ah, it was because I didn't put the last fixup upfront like the two others...
Sorry, I would have done this today, didn't managed to do it yesterday evening.
Next time first the fixups then my stuff :)

**Pull request closed without merging**
